language: ruby
node_js:
  - "7"
sudo: false
cache:
  - bundler
  - yarn
notifications:
  email: false
rvm:
  - 2.3.0
  - 2.2.2
  - jruby-9.0.3.0
before_install:
  - echo '--colour' > ~/.rspec
  - 'echo ''gem: --no-document'' > ~/.gemrc'
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
before_script: bin/setup
script: bin/rake
env:
  global:
    secure: RbWKxwfpzyQ5uv/jYH68/0J3Y9xe7rQbGULsWZT98FxZcVWLoOFlPPITmnmEK32CjQUww8iMz50FRLxFNmXg8prt1KzpzikVdIZLmYg1NFShI8+JOFhJzwCuk/LLybNUmydejR58FJvV9gS8NYqMh5leFkDM3OwLxhWdcE8hDDQ=
gemfile:
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.0.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.0.3.0
    - gemfile: gemfiles/master.gemfile
